# Play with LU and Cholesky

The pourpose of this exercise is a better understanding of **LU** and **Cholesky** decompositions through several simple examples.


Let us consider the linear system $A\mathbf{x} = \mathbf{b}$ where
$$
  A = \left(
  \begin{array}{ccc}
  \epsilon & 1 & 2\\
  1 & 3 & 1 \\
  2 & 1 & 3 \\
  \end{array}
  \right).
$$

1. Find the range of values of $\epsilon \in \mathbb{R}$ such that the matrix $A$ is symmetric and positive definite.
**Suggestion**: use the *Sylvester's criterion* which states that  a symmetric matrix $A \in \mathbb{R}^{n \times n}$ is positive definite if and only if all the main minors (The main minors of $A \in \mathbb{R}^{n \times n}$ are the determinants of the submatrices $A_p = (a_{i,j})_{1 \leq i, j \leq p}$, $p = 1, ..., n$). of $A$ are positive.
2. What factorization is more suitable for solving the linear system $A\mathbf{x}=\mathbf{b}$ for the case $\epsilon=0$? Motivate the answer.
3. Compute the Cholesky factorization $A = R^T R$ for the case $\epsilon = 2$.
4. Given $\mathbf{b} = (1,1,1)^T$, solve the linear system by using the Cholesky factorization computed at the previous point.



In [2]:
%matplotlib inline
import numpy as np

import sympy as sym
from sympy.matrices import *

import scipy.linalg

e = sym.symbols('e')

a = Matrix(([e ,1, 2], [1, 3, 1],[2, 1, 3]))

print a[0:2,0:2].det()
print a.det()


3*e - 1
8*e - 11


In [8]:
A = np.matrix(a.subs(e,2))

R = scipy.linalg.cholesky(A)

print R

[[  1.41421356e+00   7.07106781e-01   1.41421356e+00]
 [  0.00000000e+00   1.58113883e+00   1.40433339e-16]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [12]:
b = np.array([1,1,1])

y = scipy.linalg.solve(R.transpose(),b, lower=True)

x = scipy.linalg.solve(R,y)

print x

[  4.00000000e-01   2.00000000e-01   1.77635684e-16]


Let us consider the following matrix $A \in \mathbb R^{3 \times 3}$ depending on the parameter $\epsilon \in \mathbb R$:
$$
A = \left[
\begin{array}{ccc}
1 & \epsilon & -1 \\
\epsilon & \frac{35}3 & 1 \\
-1 & \epsilon & 2 \\
\end{array}
\right].
$$



1. Calculate the values of the parameter $\epsilon \in \mathbb R$ for which the matrix $A$ is invertible (non singular).

2. Calculate the Gauss factorization $LU$ of the matrix $A$ (when non singular) for a generic value of the parameter $\epsilon \in \mathbb R$.

3. Calculate the values of the parameter $\epsilon \in \mathbb R$ for which the Gauss factorization $LU$ of the matrix $A$  (when non singular) exists and is unique.

4. Set $\epsilon = \sqrt{\frac{35}3}$ and use the pivoting technique to calculate the Gauss factorization $LU$ of the matrix $A$.

5. For $\epsilon=1$, the matrix $A$ is symmetric and positive definite. Calculate the corresponding Cholesky factorization of the matrix $A$, i.e. the upper triangular matrix with positive elements on the diagonal, say $R$, for which $A = R^T R$.

In [13]:

a = Matrix(([1. ,e, -1.], [e, 35./3, 1.],[-1., e, 2.]))

print a.det()

# e = -7/3
# e = 5/3

-3.0*e**2 - 2.0*e + 11.6666666666667


In [14]:
L,U,P = a.LUdecomposition()

In [15]:
print L

Matrix([[1, 0, 0], [1.0*e, 1, 0], [-1.00000000000000, 2.0*e/(-1.0*e**2 + 11.6666666666667), 1]])


In [16]:
print U

Matrix([[1.00000000000000, e, -1.00000000000000], [0, -1.0*e**2 + 11.6666666666667, 1.0*e + 1.0], [0, 0, -2.0*e*(1.0*e + 1.0)/(-1.0*e**2 + 11.6666666666667) + 1.0]])


In [17]:
print P

[]


In [ ]:
# e +- sqrt(35/3)

In [20]:
val = np.sqrt(35./3)
print U.subs(e,val)

Matrix([[1.00000000000000, 3.41565025531987, -1.00000000000000], [0, 0, 4.41565025531987], [0, 0, zoo]])


In [21]:
P, L, U = scipy.linalg.lu(a.subs(e,val))

In [22]:
print P

[[ 0.  0.  1.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]]


In [ ]:
R = scipy.linalg.cholesky